version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: jktu20/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media

  frontend:
    container_name: foodgram_frontend
    image: jktu20/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    container_name: foodgram_gateway
    image: jktu20/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
      #- static_volume:/usr/share/nginx/html/
      #- docs:/usr/share/nginx/html/api/docs/
      #- ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    