version: '3'


volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram_backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    container_name: foodgram_frontenddocker-compose.yml
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    container_name: foodgram_gateway
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
    volumes:
      - media:/media
      - static:/staticfiles
      # - static:/usr/share/nginx/html/
      # - docs:/usr/share/nginx/html/api/docs/
      # - gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
